### ISSUE TITLE
Rename methods in MergeJoin

### ISSUE THREAD

**Issue by gjvanvuuren** [etlbox/etlbox#74]
Hi Andreas,

I pulled the latest dev branch yesterday, to have a look at the new MergeJoin functionality. I noticed that **MergeJoin.LinkTo** now requires passing the **MergeJoin.LeftJoinData** and **MergeJoin.RightJoinData** delegates.

As Left Join and Right Join are specific join operators, and the two methods have nothing to do with either a Left Join or a Right Join operation, could I ask you to please rename these methods before you update the nuget package?

Something like **MergeJoin.LeftInputData** and **MergeJoin.RightInputData** should avoid the confusion of users trying to figure out what the two methods have to do with Left Joins or Right Joins.

Regards,
Gideon

**Comment by roadrunnerlenny** [comment]
Hi @gjvanvuuren ,

thanks for letting me know!
Sure, I can change the name, I think LeftInput / RightInput or LeftInputData / RightInputData are good options. 

Because there were bigger refactorings of the underlying component linking, I wasn't able to implement the left/right join behaviour yet. Hopefully I will be able to add it in the couple of days.

**Comment by andreaslennartz** [comment]
I decided to go with `LeftInput` and `RightInput` as naming for the MergeJoin inputs. So I will close this one now. 
Still working on the the other issue to have the left / right join functionality added. 
Also, I will check if there can be additional inputs for the MergeJoin so that it allows more than two inputs.

**Comment by gjvanvuuren** [comment]
OK, thanks
