### ISSUE TITLE
source-target mapping and table structure change

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#75]
Hi Andreas

I came across ETLBox searching for an easy to learn ETL framework. I do like it a lot and I am currently going through a couple of your excercises - it's fun :-).

One of the topics I currently struggle with is how to cope with a table structure change (for example a renaming of an attribute within a table) without the need of maintaining any POCOs?
For example if I rename a database column in my target table from 'col1' to 'col1_new'. How can I make sure the mapping (targetTable.col1_new <-- sourceTable.col1) still works without changing the code? For example having a configuration file with the mapping information that then can be read at runtime.

The only way I managed to do it was with arrays and the position of the attribute within the table, see my code example below. But that is unforunately not very handy to maintain.

Thanks for your feedback!

Thanks and regards
Florian

------------------------------

            int[] targetTable = { 0, 1 };
            int[] sourceTable = { 1, 2 };

            RowTransformation<string[]> myrow2 = new RowTransformation<string[]>(
                myrow =>
                {
                    for (int i = 0; i < sourceTable.Length; i++)
                    {
                        myrow[targetTable[i]] = myrow[sourceTable[i]];
                    }
                    return myrow;
                }
            );

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

thanks for using ETLBox and your positive feedback!

Regarding your question: If I understand you correctly, your table definitions may change over you time and you don't want to adjust your POCO every time the table changes. 
Working with arrays is a valid approach, which at the beginning of ETLBox I also used when I didn't want to adjust my object every time when something changed in the source or destination.  I added the non generic implementations like `RowTransformation` without type synonymous with `RowTransformation<string[]>`. But as you already pointed out this can be sometimes a hassle to work with.

That's why I changed the non generic implementation to `RowTransformation<ExpandoObject>`. (I tried to document this in more details here: https://etlbox.net/articles/dataflow/dataflow_generic_nongeneric.html#dynamic-object-approach)

The ExpandoObject is a valid workaround to avoid having strongly typed objects before runtime.  It has two benefits: 
1) You can use it as a dynamic object and access any property without have the compiler checked if this property actually does exist
2) It is basically a wrapper for IDictionary<string, object>. You can always cast an ExpandoObject into this type and access it like a generic dictionary, e.g. use the ContainsKey() method to check if it has a property. 

Of course it does come with some downsides, but in general it's easier to work with than an array. 

So in your case, you could try out something like this (please note that this is untested code)

```
MemorySource  source = new MemorySource();
dynamic row1 = new ExpandoObject();
row1.Col1= "Test";
source.DataAsList.Add(row1);
MemorySource<ExpandoObject>  dest = new MemoryDestination<ExpandoObject>();

RowTransformation rowTrans = new RowTransformation(
{
   row => 
     IDictionary<string, object> result = new ExpandoObject();
     dynamic r = row as ExpandoObject;
     if (!((IDictionary<string, object>)r).ContainsKey("Col1"))
                        result.Add("NewColumnName", r.Col1);

});

source.LinkTo(rowTrans).LinkTo(dest);
```

Does this answer help you?

**Comment by frefardt** [comment]
Hi Andreas

Thanks for your feedback on my question. I worked through the dynamic object approach and it works very well if the column names and structure of the source and target table are the same. Or if I define the mapping explicitly inside the RowTransformation(). But how would I set the property(name) dynamically?

According to your code:

`result.Add("NewColumnName", r.Col1);`

How do I set `r.Col1` dynamically (from outside the method or class) in order to reflect a change in the name of the target column?

Regards Florian

**Comment by andreaslennartz** [comment]
Hi Florian,

ok, let's see if I get your problem right.
You have an input table that e.g. has two columns: ID and Name.
Your destination has also two columns, for simplicity they are also ID and Name. 
So the flow would directly go from the source into a destination and look like this:
```
DbSource source = new DbSource("SourceTable");
DbDestination dest = new DbDestination("DestTable");
source.LinkTo(dest);
```
All data would be copied from the source to the destination, as internally an ExpandoObject is used that would have matching property names (ID and Name).

Now in your source the column Name is renamed to FullName. 
The flow woudln't transfer this new column, as the input row now is named differently. If you would use a string array instead, the flow would still work as an array is independent from any namings. 

So we need to tell the flow that the naming in the source has changed, Name is now called FullName. Still it needs to be copied into the Name column in the destination. 

I guess the simplest way to solve this would be to pass some kind of mapping instructions to the DbDestination table. E.g. if you could pass a Mapping object that tells the DbSource that FullName should be mapped to Name, the flow would still work and your issue could be solved very easy. Can you confirm this? 

Anyways, DbDestination doesn't accept such a mapping object yet. So to solve this issue, we would need some kind of configuration object that basically keeps the information about the changed columns.

I would propose to insert a RowTransformation into the flow that handle the name changes based on this information. This could look like this:

```
DbSource source = new DbSource("SourceTable");
RowTransformation row = new RowTransformation  (
 row => {
    foreach (var change in namesChanges) {
      if (row.ContainsKey(change.OldName)
         row.Add(change.NewName, row[OldName]); 
  }
DbDestination dest = new DbDestination("DestTable");
source.LinkTo(row).LinkTo(dest);
```
The idea is to copy the data from the FullName property in the ExpandoObject into the Name property of the ExpandoObject. Then the data would then exist in the object on the properties FullName and Name, and data could be successfully inserted into the DbDestination. Optionally, you could remove the FullName property from the ExpandoObject after copying the data. 

Does that make sense to you?

**Comment by frefardt** [comment]
Hi Andreas

That makes a lot of sense to me and is exactly what I meant. A configuration object with name-mapping information that can then be passed optionaly to the DbDestination or RowTransformation (I would expect it to be on RowTransformation) would be great to have.

Regards Florian

**Comment by andreaslennartz** [comment]
That's actually good input that you would expected it on the RowTransformation and not on the DbDestination. 
Going further with this idea, it would perhaps good to have a "PropertyRenameTransformation" in place, which basically receives as input the old and new property names and then applies the renaming. It will probably only work with ExpandoObject. Perhaps this is also possible for classic POCOs, but this will probably a very hacky thing to do as it needs to find a way around the strong typing approach. 
Would such a new transformation also be something what you expect? I would then have a deeper look at this and try to come up with a prototype.

**Comment by frefardt** [comment]
Hi Andreas

I also gave this some more thoughts yesterday and would suggest to have an additional Constructor for the RowTransformation Class. It could then take a set-list (Dictionary in C# as I just learned) as an argument. The  source-target values for the column names can then be initialized like this: 

```
Dictionary<string, string> soureTargetMapping = new Dictionary<string, string>();

soureTargetMapping.Add("Column1_Source","Column1_Target");
soureTargetMapping.Add("Column2_Source","Column2_Target");

```
The new constructor for the RowTransformation Class could look like this:

`public RowTransformation(Func<TInput, TInput> rowTransformationFunc), Dictionary<string, string> sourceTargetMapping;`

or just 

`public RowTransformation(Dictionary<string, string> sourceTargetMapping;`

Invalid names in the Dictioinary would just be ignored as it is the case now.

What do you think about that approach?

Regards Florian

**Comment by andreaslennartz** [comment]
Hi Florian,

I like to the idea of using a Dictionary<string,string> for the mapping. I actually would have thought of a List<ColumnMapping>, whereby the class ColumnMapping would have the properties OldPropertyName and NewPropertyName. 
In ETLBox, I always try that all values can be set even when you use the default constructor.
So whoever calls `var trans = new RowTransformation()`, should also be allowed to add a column mapping. So I tried to have always a default constructor in place -the other constructors are only there for convenience, so that a user assign values to the properties directly through the constructor. 
However, basically you are proposing to add a Property to the RowTransformation: 

`Dictionary<string,string> SourceTargetMapping`.  

which can be initialized directly or via a constructor. The issue here is that there are actually two different row transformations:
`RowTransformation<T>`, where T can be a classic POCO, and `RowTransformation` which inherits from `RowTransformation<ExpandoObject>`. 

So the SourceTargetMapping would only work for the ExpandoObject - only here I can change the property names. This won't work for a classic POCO. 
Because of this I don't really think it should be implemented directly on the RowTransformation - it is kind of a corner-case implementation, because most people also would expect it to work with a POCO. 

I think a `RenameProperty` transformation would be better suited. It would always return an ExpandoObject, but could either work with a classic Poco or another ExpandoObject as input. In case of an input POCO it would copy each property from the POCO into the corresponding property of the ExpandoObject. 

The RenameProperty transformation would then have a property `Dictionary<string,string> SourceTargetMapping` and a corresponding constructor as you suggested. 

Does that makes sense?

**Comment by frefardt** [comment]
Hi Andreas

I like it a lot. And as it is only for ExpandoObject it makes total sense to have a separate RenameProperty transformation for it (I understand this now). Would be great to have this as an additional possibility!

Any idea on the timeline?

Thanks a lot and regards
Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,
I just uploaded a new version 2.1.2 (https://www.nuget.org/packages/ETLBox/2.1.2) which contains a new transformation: ColumnRename. It allows you to rename columns or properties.
I also updated the documentation: https://etlbox.net/articles/transformations/row_manipulations.html#columnrename
I will try to improve the example code in the next time, but it should give you the general usage idea. Let me know if you need help here.

**Comment by frefardt** [comment]
Hi @andreaslennartz 
This works fine for me now. Thanks for this feature and the documentation, highly appreciated.

Florian
