### ISSUE TITLE
Index on View

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#76]
Hi Andreas

I tried to add an index to a view with the following code on SQL Server 2019:

```
CreateIndexTask createIndexOnView = new CreateIndexTask();
createIndexTask.IndexName = "myIndex";
createIndexTask.TableName = "mySuperduperView";
createIndexTask.ConnectionManager = dbConnection_demo;
createIndexTask.Execute();
```

I didn't expect this to work because the method clearly asks for a table name. So I got this error:

`Microsoft.Data.SqlClient.SqlException: "Cannot create index on view 'mySuperduperView' because the view is not schema bound."`

I then checked your code and saw, that there is no WITH statement for creating a view. With altering the view like this I was then able to add a clustered index to it.

```
ALTER VIEW [dbo].[mySuperduperView] WITH SCHEMABINDING
AS
SELECT 
[ID],
[col1_new],
[Col2]

FROM dbo.destTable 
```

Is adding indexes for views something you consider to add as a feature to ETLBox?

Regards Florian

**Comment by andreaslennartz** [comment]
Hi Florian,

thanks for pointing this out. 

So one thing ETLBox currently does not support is to add some custom WITH statements when creating a view (or procedure). 
This is because I tried to implement the most common scenarios which will work on most databases. 

Based on my experience it is quite uncommon to create an index on a (materialized) view (mainly because of the strong limitations for schema bound views regarding outer joins, but that's another topic). The "WITH SCHEMABINDING" is something which is very particular for Sql Server. In most databases (and actually also for Sql Server), the most common approach is to create the indexes on the underlying table of the view and let the optimizer take care of using the right indexes. 

However, I can understand that you would expect some mechanism to add the "WITH SCHEMABINDING" option when you create the view using the `CreateViewTask`. So what I can think of as a feasible  approach - which would also support other databases than SqlServer - is to have a property `string AdditionalOptions` (or something similar like this). 

E.g. 

```
var createView = new CreateViewTask("TestView", "SELECT 1 AS TEST");
createView.AdditionalOptions = "WITH SCHEMABINDING";
createView.Execute();
```
would generate then for SqlServer

```
CREATE VIEW [TestView]
WITH SCHEMABINDING
AS 
SELECT 1 AS TEST
```

Is this what you had in mind?

**Comment by frefardt** [comment]
Hi Andreas 

Thanks for the feedback on this. I was just playing around with different scenarios and kind of got stuck with this 'limitation'. For me it is perfectly okay to keep this as it is.
But it would be nice to have the option to pass a complete custom sql statement to create a view including the CREATE VIEW statement.

For example:

`createViewCustom(ConnectionManagerType connectionManagerType, string definition);`

With the connectionManagerType it could then be checked if the type matches with the connection - if that is suitable.

regards
Florian

**Comment by andreaslennartz** [comment]
Hi Florian,

If you want to pass the complete SQL statement, I suggest that you simple use `SqlTask`. With SqlTask.Execute(..) you can basically run any sql code within one line.
There is a reason why the CREATE VIEW AS statement is part of the CreateViewTask - it will always work on every supported database. Though "CREATE VIEW" is the same on all supported databases, it is already different if you want to alter a view: In SqlServer it is ALTER, but in Oracle it would be "CREATE OR REPLACE". 
Of course the Sql code in the view can be very specific to a database, but at least the CREATE VIEW statement is similar. And it does include the check if the view exists (which is also very different for each database). 

So I still would be in favor of adding something like  an AdditionalOption property, so that you are in control of everything between "CREATE VIEW" and "AS".

I am not sure what you meant with checking if the type matches with the connection - do you have something in mind where the sql code is checked based on the connection?

**Comment by frefardt** [comment]
Hi Andreas

Thanks for pointing out the SqlTask.Execute() method. I didn't know about it.

A new property `string AdditionalOptions` would of course be nice to have to define the part after the CREATE VIEW statement.

The idea behind passing the ConnectionManagerType to the method is to check wheter or not the connection used to execute a custom SQL statement is suitabel. For example when I use `SqlTask.Execute()`, with a syntax for SQLServer I then could call it like this:

`SqlTask.Execute(ConnectionManagerType.SQLServer, "CREATE VIEW [dbo].[MyTable] WITH SCHEMABINDING", myConnection);`

And the method would check if the connection I use is of type SQLServer, so I don't accidentialy use a wrong connection.

regards Florian

**Comment by andreaslennartz** [comment]
Hi Florian,

I would look into adding the `AdditonalOptions` property. I will keep you updated on the progress here. 

Regarding passing the ConnectionManagerType:
If you want to check if the connection manager you are passing into the a task or component is of particular kind, I would recommend to use a code like this:
```
if (myConnection.ConnectionManagerType == ConnectionManagerType.SqlServer)
  SqlTask.Execute(myConnection, "CREATE VIEW dbo.Table);
else 
  throw new Exception ("Unexpected connection type");
```
Of course you could write your own wrapper class for this kind of checks, which is used to do the checks and then call the underlying ETLBox.

**Comment by frefardt** [comment]
Hi Andreas

That sounds plausible, I will just wrapp your class and handle it there. Thanks for your feedback.

Regards Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

version 2.1.2 now contains an improved CreateViewTask: https://etlbox.net/api/ETLBox.ControlFlow.Tasks.CreateViewTask.html#ETLBox_ControlFlow_Tasks_CreateViewTask_ViewAttributes

 It now has property ViewAttributes - 
any string added here (e.g. ViewAttributes = "WITH SCHEMABINDING" ) will create a view code with this string between the CREATE VIEW and AS statement. 

```
var createView = new CreateViewTask("TestView", "SELECT 1 AS TEST");
createView.AdditionalOptions = "WITH SCHEMABINDING";
createView.Execute();

--> 

CREATE VIEW viewname `
WITH SCHEMABINDING
AS 
  SELECT ..
```

**Comment by frefardt** [comment]
Thanks Andreas for the ViewAttribute. Works fine for me.
