### ISSUE TITLE
How to deal with auto increment ID after deleting and inserting in dbmerge?

### ISSUE THREAD

**Issue by bxjg1987** [etlbox/etlbox#80]
When dbmerge synchronizes data, the data that needs to be updated is first deleted and then inserted into the target database. If the ID in the target database is self growing, it may be referenced by other places. Does this situation cause problems?

**Comment by andreaslennartz** [comment]
Hi @bxjg1987 ,

this is actually a good point. The DbMerge currently does ignore identity / auto increment columns. So the identity value can change,  and you are right that this can cause problems when this is column is referenced somewhere else. 

I will need to revisit the current implementation, and check if there is a way that the identity column value can be preserved. Right now I am not sure if this can be easily changed, as identity columns are differently handled by each database. E.g. in Sql Server there is a way to override the identity column (SET IDENTITY_INSERT ON), I need to check how this works for other databases. 

The reason why the DbMerge does actually a delete and re-insert instead of an update are performance reasons: An update could only be executed row by row, whereby the deletion and insertion can be executed in batches which makes execution much faster. 
 
I'll keep you updated when I made progress here.

**Comment by bxjg1987** [comment]
Thank you for your reply! Availability should be superior to performance requirements. In addition, both the external and target data will arrive at memory first, and then compare, which is very memory consuming.



Whether you can add range limits to the source and target, making less data in memory.



or

All the data in the source are stored in the middle table (table provided by etlbox) and only contains the three fields, namely ID, rowversion and flag. Then, we can match the target line by line, and finally get which lines are added, which are modified and which are deleted. This intermediate state is persistent, not stored in memory.

Follow up the data stored in the middle table to perform normal data synchronization.



This approach involves persistence, performance is much lower than in memory processing, but it costs less memory.

**Comment by andreaslennartz** [comment]
Hi @bxjg1987 ,

thanks for you input. That are quite good points you make here. 
You are right, the DbMerge does store the whole destination in memory and performs the whole merge operations in memory before they are actually written back into the destination. 
Having a persistence layer in between would surely reduce the memory consumption, but on the other hand it would decrease performance at lot. This can be compared with the windows page file: this file is used to store memory pages if the memory itself is full. But whenever this process starts, your application becomes really slow. 

Having an intermediate table is a valid approach, but I also see that there are already sql solutions out there which also perform very well. E.g. in Sql Server, you can simply store your incoming data in a new table, and then use the MERGE statement to perform the data merge. Other databases also have ways to perform UPSERTs. 

So I am not quite sure if implementing a database merge that uses database tables to actually perform the merge would be really beneficial, as they would probably be slower than any merge that can be performed with sql statements.

But I admit that memory consumption could be reduced, also without an intermediate table. Currently, to detect deleted records, the whole destination table with all entries is kept in memory. But actually only the Id values of these records need to be in memory to identify deletions. To identify insert or updates, only the data rows from the destination table that are needed for the batch need to be kept in memory. 

The DbMerge depends on the LookupTransformation. The LookupTransformation is currently designed to always read all data from the lookup source into memory - there is no "partial" lookup, where some cache management is in place that only loads data from the lookup source into memory if needed. I am currently working on this kind of improvement to the lookup. Once I completed this, I also will add this to the DbMerge.

**Comment by andreaslennartz** [comment]
Hi @bxjg1987 ,

I just released version 2.2.0 (https://www.nuget.org/packages/ETLBox/2.2.0) which contains an updated DbMerge. The merge now perform bulk update operations instead of delete/inserts. This will now also work with identity columns, as the update won't  touch this column anymore. 

Unfortunately, I wasn't able to implement a solution for the memory consumption yet. The current version of the DbMerge will still load all data into memory first, and then use this information to determine the insert/update/delete statements. 
 I am working on a solution for this as well - but it will require some more work. I will let you know when I made progress here.

**Comment by bxjg1987** [comment]
@andreaslennartz Thank you very much. I'm going to set a condition when I query data so that there is as little data in memory as possible.

**Comment by andreaslennartz** [comment]
Hi @bxjg1987 ,

I just released version 2.3.0 (https://www.nuget.org/packages/ETLBox/2.3.0)
This version allows you to set the CacheMode to CacheMode.Partial on the DbMerge.
The merge operation will then load only data into memory which it needs for the currrent insert/udpate/delete operation.
