### ISSUE TITLE
EtlBox does Delete/Insert during Merge Task

### ISSUE THREAD

**Issue by arsen1991** [etlbox/etlbox#81]
EtlBox does Delete and Insert during Merge Task. That brings an error during Delete when there are foreign keys. We made this test for Postgres.

I think EtlBox should make Update instead of Delete/Insert in order to prevent foreign key errors.

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,

Thanks for your feedback and your suggestion. 
Yes, the DBMerge currently 
 converts updates into delete/inserts. 
The reason is that incoming data needs to be inserted into the target in batches. This is due to performance reasons: having a single insert/update or delete statement for every row would be very time consuming. So the DBMerge can only work properly and fast for big amounts of data if it can use operations that support bulk insert, deletes or updates.

Unfortunately, to my knowledge this bulk operations are only available for inserts and deletes .Update statements normally only work for a single row.

I wrote normally because some databases do support different syntax for bulk updates. In Sql Server, there is even a MERGE statement available, and in Postgres there is an UPDATE statement that supports bulk updates. 

But other databases don't support this update for batches, that's why I decided to convert updates into deletes/inserts. I would recommend either to remove the foreign keys before the merge and then add them again after the merge, or to use the DbDestination instead and then create your own Upsert sql statements using the specific Postgres syntax.

Please share your thoughts on this, and let me know if I have missed something.

**Comment by andreaslennartz** [comment]
Hi @arsen1991 ,

I just released version 2.2.0 (https://www.nuget.org/packages/ETLBox/2.2.0). The DbMerge now performs bulk update operations instead of delete/inserts.

So you shouldn't get any foreign key errors anymore when using the DbMerge.
