### ISSUE TITLE
Access index during Transformation

### ISSUE THREAD

**Issue by zenglei286** [etlbox/etlbox#88]
how access index during Transformation

**Comment by andreaslennartz** [comment]
Hi @zenglei286 ,
I don't understand your question.
Could you provide a lot more details, specifically:
- Some example code showing your current state?
- What are you missing?
- What do you want to achieve?
- What would be you preferred solution code-wise?

**Comment by zenglei286** [comment]
I want to page data from the data source or get the middle pieces of data

> Hi @zenglei286 ,
> I don't understand your question.
> Could you provide a lot more details, specifically:
> 
> * Some example code showing your current state?
> * What are you missing?
> * What do you want to achieve?
> * What would be you preferred solution code-wise?

**Comment by andreaslennartz** [comment]
Paging is available for all streaming source (JsonSource, CsvSource, XmlSource, ExcelSource, TextSource)

This allows you to create multiple calls to a http endpoint in order to receive all data. 

E.g. your first request to an endpoint will be via a GET request to http://test.com/data?page=1. To receive all data, you will need to increase the page number and repeat the request until you don’t get any data in the response. This can be accomplished in ETLBox with using the GetNextUri and HasNextUri properties on the source.

```C#
JsonSource<Row> source = new JsonSource<Row>();
int page = 1;
source.GetNextUri = streamMetaData => $"http://test.com/data?page="+page++;
source.HasNextUri = streamMetaData => streamMetaData.ProcessedRows > 0;
```
